Add support for Laravel Scout 9.0
algolia/scout-extended pull request #278
Opened 2021-04-29 00:15 UTC by tobz-nz

| Q                 | A
| ----------------- | ----------
| Bug fix?          no
| New feature?      no
| BC breaks?        no     
| Need Doc update   no

## Describe your change

Add support for laravel/scout 9.0

## What problem is this fixing?
With this change you can use laravel/scout ^9.0

2021-04-29 00:30 UTC, tobz-nz commented
Sigh. I was a lazy and thought this'd be a simple drop in update, I could bash out directly in github. Nope.
scout 9.0 drops support for older laravel versions and so its all a bit more involved than I have time for right now.

2021-04-29 14:04 UTC, DevinCodes requested changes
Hey @tobz-nz ! Thank you for opening this PR.

No worries about the tests, there's an issue with our test suite when it's triggered from a fork. We'll fix this soon, but for now I have to relaunch your tests manually :(

I don't think we have to drop support for older Laravel versions: Composer will resolve the right versions by itself, so we only have to add the `^9.0` constraint to `laravel/scout`, and it should work 😄

2021-04-29 14:04 UTC, DevinCodes commented on .circleci/config.yml
> +              laravel: ['^8.0']
```suggestion
              laravel: ['^6.0', '^7.0', '^8.0']
```

2021-04-29 14:04 UTC, DevinCodes commented on CHANGELOG.md
> +- Removed support for older versions of Laravel (6.0, 7.0)
```suggestion
```

2021-04-29 20:21 UTC, tobz-nz reviewed
Commited suggested changed

2021-04-29 20:23 UTC, tobz-nz commented
Cool - thanks for confirming what I suspected that tests where not working on PR's.

I did think that it should have been a pretty simple change (I did a quick manual test in an active project and everything seemed to work)

2021-04-30 07:27 UTC, DevinCodes approved these changes
Thank you for the PR! I'll release this today 🚀

2021-04-30 07:27 UTC, merged