Implement builder helper for optional filters
algolia/scout-extended pull request #284
Opened 2021-07-02 13:09 UTC by ksntcrq

Adding optional filters to the query can now be done with the `whereOptional` builder helper. It is still also possible to use `with`.

| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no     
| Related Issue     | no
| Need Doc update   | yes

## Describe your change

A new `whereOptional` builder helper is introduced to add optional filters to a search.

## What problem is this fixing?

Using the `with` helper to send optional parameters can be tedious when you have multiple of them - especially if they're conditional. With that Pull Request, it is now possible to use `whereOptional` for optional filters just like `where` can be used for filters. It also removes the necessity to build strings in the specific format Algolia expects, as it is done under the hood by the `whereOptional` implementation.

Here is an example:

```php
// Before

$optionalFilters = collect("email.provider:gmail");

if (!empty($city)) {
    $optionalFilters->push("city.code:{$city->code}");
}

if (!empty($job)) {
    $optionalFilters->push("job.title:{$job->title}");
}

User::search('killian')
    ->with([
        'optionalFilters' => $optionalFilters->join(',')
    ])
    ->get();

// After

User::search('killian')
    ->whereOptional('email.provider', 'gmail')
    ->when(!empty($city), fn ($query) => $query->whereOptional('city.name', $city->name))
    ->when(!empty($job), fn ($query) => $query->whereOptional('job.title', $job->title))
    ->get()
```

## Implementation choice

The order in which `with` and `whereOptional` are used matters. The last used will always erase the optional filters set by the other one (see unit tests). I think this is an acceptable pitfall as you should only use one or the other, but the implementation could be smarter and always override the optional filters with what's provided in `with`, for instance.

2021-07-05 14:43 UTC, DevinCodes requested changes
Hi there! Thank you for your contribution 😄 

I was wondering, do you think there's a way to make it possible to merge the `optionalFilters` when you use `with` and `whereOptional` calls? As a user, I would probably expect them all to be merged independent of the order in which I'd call them. Love to hear your thoughts on this.

2021-07-05 15:22 UTC, ksntcrq commented
> Hi @ksntcrq! Thank you for your contribution 😄
> 
> I was wondering, do you think there's a way to make it possible to merge the `optionalFilters` when you use `with` and `whereOptional` calls? As a user, I would probably expect them all to be merged independent of the order in which I'd call them. Love to hear your thoughts on this.

Let's say you read the following piece of code:

```php
User::search('killian')
    ->whereOptional('email.provider', 'gmail')
    ->with([
        'optionalFilters' => "job.title:{$job->title}",
    ])
    ->get()
```

Don't you expect `with` to _set_ the optional filters, thus overriding anything passed in `whereOptional`? To me, it's a bit of the same as doing:

```php
User::search('killian')
    ->with([
        'optionalFilters' => "email.provider:gmail",
    ])
    ->with([
        'optionalFilters' => "job.title:{$job->title}",
    ])
    ->get()
```

And, in the current implementation, the second `with` will override the first one - it won't merge both optional filters.

------

However, if you still feel like `with` and `whereOptional` should be used together, let me know and I'll be more than happy to implement it!

2021-07-07 11:32 UTC, DevinCodes approved these changes
Thanks for the reply @ksntcrq! I think you're right, let's keep the functionality the same as the current implementation to avoid confusion 🙂 

Otherwise I don't have any feedback on the PR, thank you again for the contribution!  I expect to release this later this week.

2021-07-08 10:36 UTC, ksntcrq commented
Thanks @DevinCodes!

Will you guys update the documentation or should I do something about it?

2021-07-08 14:06 UTC, merged

2021-07-08 14:06 UTC, DevinCodes commented
@ksntcrq I'll update the documentation next week, nothing to do on your side 🙂

2021-07-08 14:09 UTC, DevinCodes commented
This is released in [`v1.20.0`](https://github.com/algolia/scout-extended/releases/tag/v1.20.0). Thank you again! 🎉