Refactored the DeleteJob to use 'deleteObjects' instead of 'deleteBy'
algolia/scout-extended pull request #334
Opened 2024-01-10 05:42 UTC by simonworkhouse

| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no     
| Related Issue     | Fix #311
| Need Doc update   | yes

## Describe your change

This change is to account for the fact that the 'deleteBy' method has been deprecated on the new NeuralSearch infrastructure.

We have been advised of this by the Algolia support team and they have stated that it's a requirement in order to use the new infrastructure.

This update should also address the issue outlined in https://github.com/algolia/scout-extended/issues/311

2024-02-16 08:41 UTC, DevinCodes requested changes
Hi @simonworkhouse ,

thank you for your contribution. Apologies for the CI that didn't run as expected before, I think there's some issues with permissions for external contributors. 

I was able to run the test suite with your changes, but there are still some [failing tests](https://app.circleci.com/pipelines/github/algolia/scout-extended/265/workflows/9b742a3f-f856-475e-9421-7b0e0ae60d93/jobs/2144) that need to be addressed before this could be merged. Let me know if you run into any issues 🙂 

Thank you in advance!

2024-02-16 10:13 UTC, simonworkhouse commented
@DevinCodes No troubles, I have updated the tests to account for the updated DeleteJob behaviour.

2024-02-19 10:10 UTC, DevinCodes requested changes
Thank you again for the contribution @simonworkhouse , it seems to be working as expected. 

Going over the changes, I realized that this change has an impact on the usage of search operation: the `deleteBy` is an indexing operation, while `browse` is counted as search operation. Given that this might impact some customer's usage and billing, we may want to have this as a configurable option rather than the default behavior, which would default to using `deleteBy`. WDYT? 

I realize adding this option takes up more of your time, so let me know if you want a hand on adding this. Love to know your thoughts on it as well.

Thanks again!

2024-02-19 10:24 UTC, simonworkhouse commented
@DevinCodes We were informed by the Algolia support team that the `deleteBy` operation had been deprecated, is that not the case? Or is that perhaps just for the new "NeuralSearch" infrastructure? To be honest, I wasn't able to find that documented anywhere but the support team were adamant that it is the case.

Yes, it's probably a good idea to have it set up as a configurable option regardless, but maybe I'll first triple check with the support team just to make sure that they aren't confused.

2024-02-19 12:09 UTC, DevinCodes commented
It is deprecated only for the new infrastructure indeed: plans on the old infra should still have access to this operation 🙂

2024-02-23 03:12 UTC, simonworkhouse commented
I have added a configuration option `scout.algolia.use_deprecated_delete_by` that controls whether or not to use the deprecated `deleteBy` method. Tests have also been updated to account for both methods of deletion.

A check for this has been added into the `DeleteJob` with a default fallback value of `true` so that it does not change existing behaviour.

```php
...
if (config('scout.algolia.use_deprecated_delete_by', true)) {
...
```

I did also consider the possibility of implementing and dispatching a new Job class instead, but rejected that idea due to the potential for breaking backwards compatibility. It would have potentially caused issues if someone is either manually dispatching `DeleteJob`s or if they have extended that class.

2024-02-23 13:16 UTC, DevinCodes approved these changes
Thank you so much for the contribution @simonworkhouse, this is looking great. I'll merge and deploy a new version first thing Monday morning!

2024-02-26 09:05 UTC, merged

2024-02-26 09:09 UTC, DevinCodes commented
This is released and available in [v3.0.1](https://packagist.org/packages/algolia/scout-extended#v3.0.1)! Thank you again for your contribution!